# Form implementation generated from reading ui file 'vote_project.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(350, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(350, 400))
        Form.setMaximumSize(QtCore.QSize(350, 400))
        self.IDtextbox = QtWidgets.QTextEdit(parent=Form)
        self.IDtextbox.setGeometry(QtCore.QRect(70, 40, 211, 31))
        self.IDtextbox.setObjectName("IDtextbox")
        self.radioButton = QtWidgets.QRadioButton(parent=Form)
        self.radioButton.setGeometry(QtCore.QRect(110, 90, 99, 20))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(parent=Form)
        self.radioButton_2.setGeometry(QtCore.QRect(110, 120, 99, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(parent=Form)
        self.radioButton_3.setGeometry(QtCore.QRect(110, 150, 99, 20))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(parent=Form)
        self.radioButton_4.setGeometry(QtCore.QRect(110, 180, 99, 20))
        self.radioButton_4.setObjectName("radioButton_4")
        self.DoneButton = QtWidgets.QPushButton(parent=Form)
        self.DoneButton.setGeometry(QtCore.QRect(110, 220, 100, 32))
        self.DoneButton.setObjectName("DoneButton")
        self.ResultsButton = QtWidgets.QPushButton(parent=Form)
        self.ResultsButton.setGeometry(QtCore.QRect(110, 250, 100, 32))
        self.ResultsButton.setObjectName("ResultsButton")
        self.CandidateButton = QtWidgets.QPushButton(parent=Form)
        self.CandidateButton.setGeometry(QtCore.QRect(110, 280, 100, 32))
        self.CandidateButton.setObjectName("CandidateButton")
        self.DeleteButton = QtWidgets.QPushButton(parent=Form)
        self.DeleteButton.setGeometry(QtCore.QRect(100, 310, 121, 31))
        self.DeleteButton.setObjectName("DeleteButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.IDtextbox.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ID Number</p></body></html>"))
        self.radioButton.setText(_translate("Form", "John"))
        self.radioButton_2.setText(_translate("Form", "Jane"))
        self.radioButton_3.setText(_translate("Form", "Candidate3"))
        self.radioButton_4.setText(_translate("Form", "Candidate4"))
        self.DoneButton.setText(_translate("Form", "Submit"))
        self.ResultsButton.setText(_translate("Form", "Show Results"))
        self.CandidateButton.setText(_translate("Form", "Add Candidate"))
        self.DeleteButton.setText(_translate("Form", "Delete Candidate"))
